name: Build,lint & test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Running make
      run: make
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        file: ./.coverage/cover.out
        fail_ci_if_error: true
