name: Build,lint & test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59
    - name: Tests
      run: |
        mkdir -p .coverage
        go test -race -coverprofile=.coverage/cover.out -covermode=atomic
    - name: Codecov
      uses: codecov/codecov-action@v4.5.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        file: ./.coverage/cover.out
        fail_ci_if_error: true
